// UI regression against the local app. Real endpoints are read-only; mutations are stubbed.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:1366,height:768}});
  const errors = [], blockedWrites = [], checks = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/**', async route => {
    if (!['GET','HEAD'].includes(route.request().method())) {
      blockedWrites.push(route.request().url()); await route.abort();
    } else await route.continue();
  });
  const ok = (name, condition) => { assert.ok(condition, name); checks.push(name); };
  const shot = async name => page.screenshot({path:path.join(__dirname, name+'.png'),animations:'disabled'});
  await page.goto('http://127.0.0.1:8765');
  await page.waitForSelector('.home-task-row');
  ok('home has exactly one composer', await page.locator('#composerInput').count() === 1);
  ok('empty send disabled', await page.locator('#sendBtn').isDisabled());
  ok('three recent tasks visible above fold', await page.locator('.home-task-row').last().evaluate(e => e.getBoundingClientRect().bottom < innerHeight));
  await shot('desktop');
  await page.locator('.home-shortcut').first().click();
  ok('shortcut populates draft and enables send', (await page.inputValue('#composerInput')).includes('报告') && await page.locator('#sendBtn').isEnabled());
  await page.locator('#composerInput').fill('首页草稿');
  await page.locator('.home-task-row').first().click();
  await page.waitForSelector('.in-task');
  ok('existing task does not inherit home draft', await page.inputValue('#composerInput') === '');
  const active = await page.evaluate(() => RT.workspace.activeId());
  await page.locator('#composerInput').fill('对话草稿');
  await page.evaluate(() => {
    window.originalGetTask = RT.api.getTask;
    RT.api.getTask = () => new Promise(resolve => {window.resolveStaleTask = resolve;});
    RT.workspace.openExisting('stale-task');
    RT.workspace.showSettings();
    window.resolveStaleTask({id:'stale-task',title:'Should not replace settings',runs:[]});
    RT.api.getTask = window.originalGetTask;
  });
  await page.waitForTimeout(100);
  ok('late task response cannot replace settings', await page.locator('.settings').isVisible());
  await page.evaluate(id => RT.workspace.openExisting(id), active);
  await page.locator('#navSettings').click();
  await page.waitForSelector('.settings');
  ok('settings hides but retains composer', await page.locator('#composerInput').count() === 1 && !(await page.locator('#composerInput').isVisible()));
  await page.evaluate(() => RT.workspace.openExisting(RT.workspace.activeId()));
  await page.waitForSelector('.in-task');
  ok('conversation draft survives settings', await page.inputValue('#composerInput') === '对话草稿');
  await shot('conversation');
  await page.locator('#newDraftBtn').click();
  await page.waitForSelector('.home-dashboard');
  ok('new task clears active task and folder', await page.evaluate(() => RT.workspace.activeId() === null) && (await page.locator('#btnNewTask').innerText()).includes('可选'));
  ok('home draft restored', await page.inputValue('#composerInput') === '首页草稿');
  await page.locator('#navTasks').click();
  await page.waitForSelector('.task-filter-input');
  ok('all tasks accessible beyond old eight-row cap', await page.locator('.home-task-row').count() > 8);
  await page.locator('.task-filter-input').fill('NOT-A-REAL-TASK-9908');
  ok('search empty state', await page.locator('.home-task-row').count() === 0 && await page.locator('.home-empty').isVisible());
  await page.locator('#navRunning').click();
  await page.waitForTimeout(250);
  ok('status filter heading', await page.locator('.home-section-head h2').innerText() === '进行中');
  await page.locator('#btnSearch').click();
  await page.waitForSelector('.search-overlay.show');
  await page.keyboard.press('Escape');
  ok('global search opens and closes', !(await page.locator('.search-overlay').isVisible()));
  await page.locator('#sidebarCollapse').click();
  await page.waitForTimeout(280);
  ok('desktop sidebar collapse', !(await page.locator('#taskSidebar').isVisible()));
  await page.locator('#sidebarToggle').click();
  await page.waitForTimeout(280);
  ok('desktop sidebar restore', await page.locator('#taskSidebar').isVisible());
  await page.evaluate(() => RT.workspace.goHome());
  await page.locator('#composerInput').fill('');
  await page.evaluate(() => document.documentElement.setAttribute('data-theme','light'));
  await shot('light');
  await page.evaluate(() => document.documentElement.setAttribute('data-theme','dark'));
  for (const [width,height] of [[1440,900],[1024,768],[768,1024],[390,844],[320,640]]) {
    await page.setViewportSize({width,height});
    await page.waitForTimeout(300);
    ok(`no horizontal overflow ${width}`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    ok(`composer in bounds ${width}`, await page.locator('.composer').evaluate(e => {const r=e.getBoundingClientRect();return r.x>=0 && r.right<=innerWidth && r.bottom < innerHeight;}));
    await shot('viewport-'+width);
  }
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(300);
  await shot('mobile');
  ok('mobile sidebar hidden and inert', await page.locator('#taskSidebar').evaluate(e => e.inert && getComputedStyle(e).visibility==='hidden'));
  await page.locator('#sidebarToggle').click();
  await page.waitForTimeout(300);
  ok('mobile sidebar opens', await page.locator('#sidebarToggle').getAttribute('aria-expanded') === 'true');
  await shot('mobile-navigation');
  await page.locator('#sidebarCollapse').click();
  await page.waitForTimeout(300);
  ok('mobile sidebar closes', await page.locator('#sidebarToggle').getAttribute('aria-expanded') === 'false');
  await page.locator('#composerInput').fill('手机换行');
  await page.locator('#composerInput').press('Enter');
  ok('mobile Enter inserts newline', (await page.inputValue('#composerInput')).includes('\n'));
  await page.evaluate(id => RT.workspace.openExisting(id), active);
  await page.waitForSelector('.in-task');
  ok('mobile conversation uses full content column', await page.locator('.in-task').evaluate(e => e.getBoundingClientRect().width >= innerWidth - 24));
  await shot('mobile-conversation');
  await page.setViewportSize({width:1366,height:768});
  await page.evaluate(() => RT.workspace.goHome());
  await page.locator('#composerInput').fill('中文输入');
  await page.locator('#composerInput').dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,keyCode:229});
  ok('IME Enter does not submit', await page.inputValue('#composerInput') === '中文输入');
  await page.evaluate(() => { window.created = []; RT.api.createProject = async payload => { window.created.push(payload); throw new Error('intentional UI-only submission check'); }; });
  await page.locator('#sendBtn').click();
  await page.waitForTimeout(100);
  ok('new home submits through createProject', await page.evaluate(() => window.created.length === 1 && window.created[0].name === '中文输入'));
  // Verify folder binding without invoking the native picker or modifying a real task.
  await page.evaluate(async id => {
    await RT.workspace.openExisting(id);
    window.folderUpdates = [];
    RT.api.pickWorkLocation = async () => ({path:'C:/ui-test/Example'});
    RT.api.listWorkLocations = async () => [{id:9908,name:'Example',local_path:'C:/ui-test/Example'}];
    RT.api.updateProject = async (id, payload) => {window.folderUpdates.push({id,payload});return {};};
  }, active);
  await page.locator('#btnNewTask').click();
  await page.waitForTimeout(100);
  ok('folder selection updates existing task', await page.evaluate(id => window.folderUpdates.length === 1 && window.folderUpdates[0].id === id && RT.workspace.activeId() === id,active));
  ok('folder label concise with full path in tooltip', await page.locator('#btnNewTask').innerText() === 'Example' && (await page.locator('#btnNewTask').getAttribute('title')).includes('C:/ui-test/Example'));
  await page.evaluate(async () => {
    await RT.workspace.goHome();
    window.uploadOwners = [];
    RT.api.createProject = async () => ({id:'ui-only-upload-owner',title:'UI upload test'});
    RT.api.uploadProjectAttachment = async (id,file,name) => {window.uploadOwners.push(id);return {ok:true,attachment:{id:9909,attachment_scope:'message_only'}};};
  });
  await page.locator('#btnComposerFile').click();
  const chooser = page.waitForEvent('filechooser');
  await page.locator('#composerFileMenu [data-kind="upload"]').click();
  await (await chooser).setFiles({name:'ui-test.txt',mimeType:'text/plain',buffer:Buffer.from('UI test only')});
  await page.waitForTimeout(150);
  ok('new-home attachment gets a project before uploading', await page.evaluate(() => window.uploadOwners[0] === 'ui-only-upload-owner'));
  ok('uploaded attachment enables send', await page.locator('#composerChips').innerText().then(t=>t.includes('ui-test.txt')) && await page.locator('#sendBtn').isEnabled());
  await page.evaluate(() => {RT.api.getProject = async () => ({sources:[{id:9910,display_name:'Source document'}]});});
  await page.locator('#btnComposerFile').click();
  await page.locator('#composerFileMenu [data-kind="source"]').click();
  await page.locator('#composerFileMenu').getByRole('button',{name:'返回',exact:true}).click();
  const chooserAfterSources = page.waitForEvent('filechooser');
  await page.locator('#composerFileMenu [data-kind="upload"]').click();
  await (await chooserAfterSources).setFiles([]);
  ok('upload picker still works after leaving sources menu', true);
  ok('no writes reached real API', blockedWrites.length === 0);
  ok('no browser exceptions', errors.length === 0);
  fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({checks,errors,blockedWrites},null,2));
  console.log(checks.map(c=>'PASS '+c).join('\n'));
  await browser.close();
})().catch(e => { console.error(e);process.exit(1); });
